THEMES = [
    {"name": "Général", "keywords": []},
    {
        "name": "Cinéma",
        "keywords": [
            "film",
            "cinema",
            "cinéma",
            "movie",
            "acteur",
            "actrice",
            "réalisateur",
            "realisateur",
            "oscar",
            "festival de cannes",
            "marvel",
            "star wars",
            "netflix film",
        ],
    },
    {
        "name": "Séries & TV",
        "keywords": [
            "série",
            "tv",
            "show",
            "netflix",
            "hbo",
            "prime video",
            "disney+",
            "anime",
            "saison",
        ],
    },
    {
        "name": "Jeux vidéo",
        "keywords": [
            "jeu video",
            "jeux video",
            "jeux vidéo",
            "nintendo",
            "playstation",
            "xbox",
            "steam",
            "minecraft",
            "fortnite",
            "gta",
            "call of duty",
            "pokemon",
            "zelda",
            "league of legends",
            "valorant",
            "fifa",
            "switch",
            "mobile game",
        ],
    },
    {
        "name": "Musique",
        "keywords": [
            "musique",
            "album",
            "chanson",
            "chanteur",
            "chanteuse",
            "rap",
            "pop",
            "rock",
            "dj",
            "concert",
            "festival",
            "grammy",
        ],
    },
    {
        "name": "Sport",
        "keywords": [
            "football",
            "foot",
            "nba",
            "tennis",
            "rugby",
            "sport",
            "olympique",
            "tour de france",
            "roland garros",
            "coupe du monde",
            "championnat",
            "ligue",
            "f1",
        ],
    },
    {
        "name": "Sciences",
        "keywords": [
            "science",
            "physique",
            "chimie",
            "biologie",
            "astronomie",
            "espace",
            "nasa",
            "esa",
            "robotique",
            "recherche",
        ],
    },
    {"name": "Pays", "keywords": []},
    {
        "name": "Voyage & Culture",
        "keywords": [
            "tourisme",
            "ville",
            "monument",
            "patrimoine",
            "culture",
            "tradition",
            "cuisine",
            "route",
            "paysage",
        ],
    },
    {
        "name": "Personnalités",
        "keywords": [
            "né ",
            "née ",
            "acteur",
            "actrice",
            "politicien",
            "politicienne",
            "président",
            "president",
            "chanteur",
            "chanteuse",
            "journaliste",
            "entrepreneur",
            "scientifique",
            "influenceur",
        ],
    },
    {
        "name": "Technologie",
        "keywords": [
            "tech",
            "technologie",
            "informatique",
            "logiciel",
            "internet",
            "open source",
            "IA",
            "intelligence artificielle",
            "google",
            "microsoft",
            "apple",
            "amazon",
            "meta",
            "facebook",
            "chatgpt",
            "cybersécurité",
            "startup",
        ],
    },
    {
        "name": "Économie & Business",
        "keywords": [
            "bourse",
            "entreprise",
            "finance",
            "banque",
            "start-up",
            "investissement",
            "bitcoin",
            "cryptomonnaie",
            "économie",
        ],
    },
    {
        "name": "Histoire & Politique",
        "keywords": [
            "révolution",
            "guerre",
            "empire",
            "royaume",
            "politique",
            "élection",
            "traité",
            "constitution",
        ],
    },
]
