THEMES = [
    {"name": "Général", "keywords": []},
    {"name": "Cinéma", "keywords": ["film", "cinema", "cinéma", "movie", "acteur", "actrice", "réalisateur", "realisateur", "oscar"]},
    {
        "name": "Jeux vidéo",
        "keywords": [
            "jeu video",
            "jeux video",
            "jeux vidéo",
            "nintendo",
            "playstation",
            "xbox",
            "steam",
            "minecraft",
            "fortnite",
            "gta",
            "call of duty",
            "pokemon",
            "zelda",
            "league of legends",
            "lol ",
            "valorant",
            "fifa",
            "switch",
        ],
    },
    {
        "name": "Musique",
        "keywords": [
            "musique",
            "album",
            "chanson",
            "chanteur",
            "chanteuse",
            "rap",
            "pop",
            "rock",
            "dj",
            "concert",
        ],
    },
    {
        "name": "Sport",
        "keywords": [
            "football",
            "foot",
            "nba",
            "tennis",
            "rugby",
            "sport",
            "olympique",
            "tour de france",
            "roland garros",
            "coupe du monde",
        ],
    },
    {"name": "Pays", "keywords": []},
    {
        "name": "Personnalités",
        "keywords": [
            "né ",
            "née ",
            "acteur",
            "actrice",
            "politicien",
            "politicienne",
            "président",
            "president",
            "chanteur",
            "chanteuse",
            "journaliste",
        ],
    },
    {
        "name": "Technologie",
        "keywords": [
            "tech",
            "technologie",
            "informatique",
            "logiciel",
            "internet",
            "open source",
            "IA",
            "intelligence artificielle",
            "google",
            "microsoft",
            "apple",
            "amazon",
            "meta",
            "facebook",
            "chatgpt",
        ],
    },
]
